[project]
name = "ComfyUI_EasyKitHT_NodeAlignPro"
description = "ComfyUI_EasyKitHT_NodeAlignPro is a lightweight ComfyUI node alignment and node coloring tool for refactoring and rewriting the UI based on the open-source projects Comfyui-Align and Comfyui-Nodealigner."
version = "v2.0.1_rc"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/ArtsticH/ComfyUI_EasyKitHT_NodeAlignPro"

[tool.comfy]
PublisherId = "ArtsticH"
DisplayName = "EasyKitHT NodeAlignPro"
Icon = "ArtsticH/hNodeAlignPro__hBtnY_barLOGO@8x.png"
