[project]
name = "EasyKitHT NodeAlignPro"
description = "Professional alignment & real-time node color picker. A must-have plugin for managing node layout and color schemes in ComfyUI. Features a real-time color picker, alignment, 7 preset colors, grayscale/custom modes, and one-click reverse alignment."
version = "2.0.3"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/ArtsticH/ComfyUI_EasyKitHT_NodeAlignPro"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "ArtsticH"
DisplayName = "EasyKitHT NodeAlignPro"
Icon = "web/hNodeAlignPro__hBtnY_barLOGO@8x.png"
